### ISSUE TITLE
Обновление query-string

### ISSUE THREAD

**Issue by dartess** [fullstack-development/build-route-tree#8]
Привет! Возможно ли обновить `query-string` до 6.3+ и удалить `@types/query-string`? Как раз в 6.3 были добавлены встроенные типы (это единственное изменение в пакете - https://diff.intrinsic.com/query-string/6.2.0/6.3.0). Сейчас из-за этого при установке пакета ворнинг:

```
npm WARN deprecated @types/query-string@6.3.0: This is a stub types definition. query-string provides its own type definitions, so you do not need this installed.
```

Другие варианты - обновить пакет до последней минорной версии или до последней мажорной (breaking changes, вероятно, в этом случае и build-route-tree поднять до 2-й версии надо будет)

Могу сделать реквест с выбранным вариантом

**Comment by in19farkt** [comment]
@dartess судя по всему `@types/query-string` должен находиться в devDependencies, т.к. в итоговые d.ts файлы оно не попадает и соответственно мы не видим ошибок сборки из-за отсутствия типов для `query-string`.

Чтобы убрать ворнинг можно руками в yarn.lock или package.lock заменить версию `@types/query-string` на последнюю не пустую, возможно это `6.2.0`.

**Comment by in19farkt** [comment]
@Znack Привет) возможно вам стоит подумать как и кто должен контрибьютить в этот пакет, возможно как-то автоматизировать публикацию новых версий

**Comment by dartess** [comment]
@in19farkt я не совсем понял логику, зачем нужен пустой/не пустой `@types/query-string` в devDependencies, если можно просто обновить query-string до 6.3.0 и получить типы для разработки оттуда? Я на всякий случай проверил, билд после удаления сторонних типов и обновления до 6.3 выдаёт абсолютно тот же результат)

За ворнинг спасибо, но хочется по красивому сделать)

**Comment by in19farkt** [comment]
@dartess я говорил про зависимости самого пакета `build-route-tree`, эти типы нужны на этапе сборки пакета, а в итоговых d.ts файлах нет импортов из `query-string`, соответственно можно убрать `@types/query-string` в devDependencies, опубликовать новую версию и ворнинга больше не будет

**Comment by dartess** [comment]
Я тоже про зависимости пакета `build-route-tree`. Эти типы не нужны в виде отдельного пакета, они есть в самом пакете `query-string`, начиная с 6.3. Если под "этапом сборки пакета" подразумевается `npm run build`, повторюсь, он прекрасно работает без `@types/query-string` при условии обновления `query-string` до версии с типами.
